"""add model_type to face_embeddings

Revision ID: 24503d6b612e
Revises: 7c16fbffd54f
Create Date: 2025-06-20 16:52:17.519777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24503d6b612e'
down_revision: Union[str, None] = '7c16fbffd54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_embeddings', sa.Column('model_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_face_embeddings_model_type'), 'face_embeddings', ['model_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_embeddings_model_type'), table_name='face_embeddings')
    op.drop_column('face_embeddings', 'model_type')
    # ### end Alembic commands ###
