"""add_student_and_staff_ids

Revision ID: 7d8c05b6f491
Revises: 666ad0d36984
Create Date: 2025-05-26 16:26:04.778266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8c05b6f491'
down_revision: Union[str, None] = '666ad0d36984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('staff_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_staff_id'), 'users', ['staff_id'], unique=True)
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.drop_index(op.f('ix_users_staff_id'), table_name='users')
    op.drop_column('users', 'staff_id')
    op.drop_column('users', 'student_id')
    # ### end Alembic commands ###
