"""add registration_group_id to face_embeddings

Revision ID: d42e492a79a6
Revises: 24503d6b612e
Create Date: 2025-06-20 21:52:29.433554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42e492a79a6'
down_revision: Union[str, None] = '24503d6b612e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_embeddings', sa.Column('registration_group_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_face_embeddings_registration_group_id'), 'face_embeddings', ['registration_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_embeddings_registration_group_id'), table_name='face_embeddings')
    op.drop_column('face_embeddings', 'registration_group_id')
    # ### end Alembic commands ###
